// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp32_p4_eye_factory

#include "../ui.h"

void ui_ScreenCamera_screen_init(void)
{
    ui_ScreenCamera = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // ui_PanelCanvas = lv_obj_create(ui_ScreenCamera);
    ui_PanelCanvas = lv_canvas_create(ui_ScreenCamera);
    lv_obj_set_width(ui_PanelCanvas, 240);
    lv_obj_set_height(ui_PanelCanvas, 240);
    lv_obj_set_align(ui_PanelCanvas, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelCanvas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCanvasSelect = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageCanvasSelect, &ui_img_button_select_png);
    lv_obj_set_width(ui_ImageCanvasSelect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCanvasSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCanvasSelect, 100);
    lv_obj_set_y(ui_ImageCanvasSelect, -47);
    lv_obj_set_align(ui_ImageCanvasSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCanvasSelect, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCanvasSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCanvasUp = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageCanvasUp, &ui_img_up_button_png);
    lv_obj_set_width(ui_ImageCanvasUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCanvasUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCanvasUp, 100);
    lv_obj_set_y(ui_ImageCanvasUp, 0);
    lv_obj_set_align(ui_ImageCanvasUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCanvasUp, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCanvasUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCanvasDown = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageCanvasDown, &ui_img_button_down_png);
    lv_obj_set_width(ui_ImageCanvasDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCanvasDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCanvasDown, 100);
    lv_obj_set_y(ui_ImageCanvasDown, 55);
    lv_obj_set_align(ui_ImageCanvasDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCanvasDown, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCanvasDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelCanvasMaskLarge = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasMaskLarge, 240);
    lv_obj_set_height(ui_PanelCanvasMaskLarge, 240);
    lv_obj_set_x(ui_PanelCanvasMaskLarge, -134);
    lv_obj_set_y(ui_PanelCanvasMaskLarge, 0);
    lv_obj_set_align(ui_PanelCanvasMaskLarge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasMaskLarge, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasMaskLarge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasMaskLarge, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasMaskLarge, lv_color_hex(0xD6D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasMaskLarge, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasMaskLarge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasMaskLarge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupCamera = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasPopupCamera, 156);
    lv_obj_set_height(ui_PanelCanvasPopupCamera, 132);
    lv_obj_set_x(ui_PanelCanvasPopupCamera, -3);
    lv_obj_set_y(ui_PanelCanvasPopupCamera, -12);
    lv_obj_set_align(ui_PanelCanvasPopupCamera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasPopupCamera, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasPopupCamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasPopupCamera, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCamera, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCamera, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasPopupCamera, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasPopupCamera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraTop = lv_label_create(ui_PanelCanvasPopupCamera);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraTop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraTop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraTop, -1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraTop, -31);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraTop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraTop, "Camera Mode");
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraTop, &ui_font_FontKoHoBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupCameraLine = lv_obj_create(ui_PanelCanvasPopupCamera);
    lv_obj_set_width(ui_PanelCanvasPopupCameraLine, 141);
    lv_obj_set_height(ui_PanelCanvasPopupCameraLine, 6);
    lv_obj_set_x(ui_PanelCanvasPopupCameraLine, 0);
    lv_obj_set_y(ui_PanelCanvasPopupCameraLine, -12);
    lv_obj_set_align(ui_PanelCanvasPopupCameraLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvasPopupCameraLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCameraLine, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCameraLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraDown = lv_label_create(ui_PanelCanvasPopupCamera);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraDown, -1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraDown, 22);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraDown, "Rotate wheel to\n   adjust zoom");
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraDown, &ui_font_FontKoHoMiniBold14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCanvasSDcard = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageCanvasSDcard, &ui_img_sdcard_no_png);
    lv_obj_set_width(ui_ImageCanvasSDcard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCanvasSDcard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCanvasSDcard, -102);
    lv_obj_set_y(ui_ImageCanvasSDcard, -101);
    lv_obj_set_align(ui_ImageCanvasSDcard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCanvasSDcard, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCanvasSDcard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCanvasMenu = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageCanvasMenu, &ui_img_button_menu_png);
    lv_obj_set_width(ui_ImageCanvasMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCanvasMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCanvasMenu, 100);
    lv_obj_set_y(ui_ImageCanvasMenu, -47);
    lv_obj_set_align(ui_ImageCanvasMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCanvasMenu, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCanvasMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCanvas2X = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvas2X, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvas2X, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvas2X, 100);
    lv_obj_set_y(ui_LabelCanvas2X, 0);
    lv_obj_set_align(ui_LabelCanvas2X, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvas2X, "2X");
    lv_obj_add_flag(ui_LabelCanvas2X, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_LabelCanvas2X, &ui_font_FontKoHoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCanvas3X = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvas3X, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvas3X, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvas3X, 100);
    lv_obj_set_y(ui_LabelCanvas3X, 55);
    lv_obj_set_align(ui_LabelCanvas3X, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvas3X, "3X");
    lv_obj_add_flag(ui_LabelCanvas3X, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_LabelCanvas3X, &ui_font_FontKoHoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCanvasFactor = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvasFactor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvasFactor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvasFactor, 0);
    lv_obj_set_y(ui_LabelCanvasFactor, -100);
    lv_obj_set_align(ui_LabelCanvasFactor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvasFactor, "1.0X");
    lv_obj_add_flag(ui_LabelCanvasFactor, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_LabelCanvasFactor, &ui_font_FontKoHoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasMaskCamera = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasMaskCamera, 100);
    lv_obj_set_height(ui_PanelCanvasMaskCamera, 87);
    lv_obj_set_x(ui_PanelCanvasMaskCamera, -120);
    lv_obj_set_y(ui_PanelCanvasMaskCamera, 0);
    lv_obj_set_align(ui_PanelCanvasMaskCamera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasMaskCamera, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasMaskCamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasMaskCamera, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasMaskCamera, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasMaskCamera, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasMaskCamera, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasMaskCamera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePanelCanvasMaskCamera = lv_img_create(ui_PanelCanvasMaskCamera);
    lv_img_set_src(ui_ImagePanelCanvasMaskCamera, &ui_img_camera_small_png);
    lv_obj_set_width(ui_ImagePanelCanvasMaskCamera, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelCanvasMaskCamera, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePanelCanvasMaskCamera, 20);
    lv_obj_set_y(ui_ImagePanelCanvasMaskCamera, 0);
    lv_obj_set_align(ui_ImagePanelCanvasMaskCamera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePanelCanvasMaskCamera, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelCanvasMaskCamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelCanvasPopupCameraInterval = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasPopupCameraInterval, 156);
    lv_obj_set_height(ui_PanelCanvasPopupCameraInterval, 132);
    lv_obj_set_x(ui_PanelCanvasPopupCameraInterval, -3);
    lv_obj_set_y(ui_PanelCanvasPopupCameraInterval, -12);
    lv_obj_set_align(ui_PanelCanvasPopupCameraInterval, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasPopupCameraInterval, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasPopupCameraInterval, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasPopupCameraInterval, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCameraInterval, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCameraInterval, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasPopupCameraInterval, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasPopupCameraInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraTopInterval = lv_label_create(ui_PanelCanvasPopupCameraInterval);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraTopInterval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraTopInterval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraTopInterval, -1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraTopInterval, -35);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraTopInterval, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraTopInterval, "      Interval \n  Camera Mode");
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraTopInterval, &ui_font_FontKoHoBold18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupCameraIntervalLine = lv_obj_create(ui_PanelCanvasPopupCameraInterval);
    lv_obj_set_width(ui_PanelCanvasPopupCameraIntervalLine, 141);
    lv_obj_set_height(ui_PanelCanvasPopupCameraIntervalLine, 6);
    lv_obj_set_x(ui_PanelCanvasPopupCameraIntervalLine, 0);
    lv_obj_set_y(ui_PanelCanvasPopupCameraIntervalLine, -12);
    lv_obj_set_align(ui_PanelCanvasPopupCameraIntervalLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvasPopupCameraIntervalLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCameraIntervalLine, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCameraIntervalLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraIntervalDown = lv_label_create(ui_PanelCanvasPopupCameraInterval);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraIntervalDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraIntervalDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraIntervalDown, 2);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraIntervalDown, 27);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraIntervalDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraIntervalDown, " 1)Set Interval\n2)Press wheel to \nstart shooting");
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraIntervalDown, &ui_font_FontKoHoMiniBold14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasMaskCameraInterval = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasMaskCameraInterval, 100);
    lv_obj_set_height(ui_PanelCanvasMaskCameraInterval, 87);
    lv_obj_set_x(ui_PanelCanvasMaskCameraInterval, -120);
    lv_obj_set_y(ui_PanelCanvasMaskCameraInterval, 0);
    lv_obj_set_align(ui_PanelCanvasMaskCameraInterval, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasMaskCameraInterval, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasMaskCameraInterval, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasMaskCameraInterval, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasMaskCameraInterval, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasMaskCameraInterval, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasMaskCameraInterval, lv_color_hex(0xC9C9C9),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasMaskCameraInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePanelCanvasMaskCameraInterval = lv_img_create(ui_PanelCanvasMaskCameraInterval);
    lv_img_set_src(ui_ImagePanelCanvasMaskCameraInterval, &ui_img_interval_small_png);
    lv_obj_set_width(ui_ImagePanelCanvasMaskCameraInterval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelCanvasMaskCameraInterval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePanelCanvasMaskCameraInterval, 20);
    lv_obj_set_y(ui_ImagePanelCanvasMaskCameraInterval, 0);
    lv_obj_set_align(ui_ImagePanelCanvasMaskCameraInterval, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePanelCanvasMaskCameraInterval, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelCanvasMaskCameraInterval, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCanvas5mplus = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvas5mplus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvas5mplus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvas5mplus, 100);
    lv_obj_set_y(ui_LabelCanvas5mplus, 0);
    lv_obj_set_align(ui_LabelCanvas5mplus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvas5mplus, "+5m");
    lv_obj_add_flag(ui_LabelCanvas5mplus, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_LabelCanvas5mplus, &ui_font_FontKoHoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCanvas5mSub = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvas5mSub, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvas5mSub, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvas5mSub, 100);
    lv_obj_set_y(ui_LabelCanvas5mSub, 55);
    lv_obj_set_align(ui_LabelCanvas5mSub, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvas5mSub, "-5m");
    lv_obj_add_flag(ui_LabelCanvas5mSub, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_LabelCanvas5mSub, &ui_font_FontKoHoBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCanvasInvervalTime = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvasInvervalTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvasInvervalTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvasInvervalTime, -90);
    lv_obj_set_y(ui_LabelCanvasInvervalTime, 100);
    lv_obj_set_align(ui_LabelCanvasInvervalTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvasInvervalTime, "30min");
    lv_obj_add_flag(ui_LabelCanvasInvervalTime, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_PanelCanvasPopupVideoMode = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasPopupVideoMode, 156);
    lv_obj_set_height(ui_PanelCanvasPopupVideoMode, 132);
    lv_obj_set_x(ui_PanelCanvasPopupVideoMode, -3);
    lv_obj_set_y(ui_PanelCanvasPopupVideoMode, -12);
    lv_obj_set_align(ui_PanelCanvasPopupVideoMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasPopupVideoMode, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasPopupVideoMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasPopupVideoMode, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupVideoMode, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupVideoMode, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasPopupVideoMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasPopupVideoMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupVideoModeTop = lv_label_create(ui_PanelCanvasPopupVideoMode);
    lv_obj_set_width(ui_LabelPanelCanvasPopupVideoModeTop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupVideoModeTop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupVideoModeTop, -2);
    lv_obj_set_y(ui_LabelPanelCanvasPopupVideoModeTop, -34);
    lv_obj_set_align(ui_LabelPanelCanvasPopupVideoModeTop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupVideoModeTop, "Video Mode");
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupVideoModeTop, &ui_font_FontKoHoBold18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupVideoModeLine = lv_obj_create(ui_PanelCanvasPopupVideoMode);
    lv_obj_set_width(ui_PanelCanvasPopupVideoModeLine, 141);
    lv_obj_set_height(ui_PanelCanvasPopupVideoModeLine, 6);
    lv_obj_set_x(ui_PanelCanvasPopupVideoModeLine, 0);
    lv_obj_set_y(ui_PanelCanvasPopupVideoModeLine, -12);
    lv_obj_set_align(ui_PanelCanvasPopupVideoModeLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvasPopupVideoModeLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupVideoModeLine, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupVideoModeLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupVideoModeDown = lv_label_create(ui_PanelCanvasPopupVideoMode);
    lv_obj_set_width(ui_LabelPanelCanvasPopupVideoModeDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupVideoModeDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupVideoModeDown, -1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupVideoModeDown, 22);
    lv_obj_set_align(ui_LabelPanelCanvasPopupVideoModeDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupVideoModeDown, "Rotate wheel to \n  adjust zoom.");
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupVideoModeDown, &ui_font_FontKoHoMiniBold14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasMaskVideoMode = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasMaskVideoMode, 100);
    lv_obj_set_height(ui_PanelCanvasMaskVideoMode, 87);
    lv_obj_set_x(ui_PanelCanvasMaskVideoMode, -120);
    lv_obj_set_y(ui_PanelCanvasMaskVideoMode, 0);
    lv_obj_set_align(ui_PanelCanvasMaskVideoMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasMaskVideoMode, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasMaskVideoMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasMaskVideoMode, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasMaskVideoMode, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasMaskVideoMode, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasMaskVideoMode, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasMaskVideoMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePanelCanvasMaskVideoMode = lv_img_create(ui_PanelCanvasMaskVideoMode);
    lv_img_set_src(ui_ImagePanelCanvasMaskVideoMode, &ui_img_video_small_png);
    lv_obj_set_width(ui_ImagePanelCanvasMaskVideoMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelCanvasMaskVideoMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePanelCanvasMaskVideoMode, 20);
    lv_obj_set_y(ui_ImagePanelCanvasMaskVideoMode, 0);
    lv_obj_set_align(ui_ImagePanelCanvasMaskVideoMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePanelCanvasMaskVideoMode, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelCanvasMaskVideoMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
