// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: eye_s3_product_test

#include "../ui.h"

void ui_ScreenColor_screen_init(void)
{
    ui_ScreenColor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenColor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
