// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: eye_s3_product_test

#include "../ui.h"

void ui_ScreenSuccess_screen_init(void)
{
    ui_ScreenSuccess = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSuccess, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSuccess = lv_label_create(ui_ScreenSuccess);
    lv_obj_set_width(ui_LabelSuccess, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSuccess, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSuccess, 1);
    lv_obj_set_y(ui_LabelSuccess, -23);
    lv_obj_set_align(ui_LabelSuccess, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSuccess, "您已完成所有测试");
    lv_obj_set_style_text_font(ui_LabelSuccess, &ui_font_FontPromt, LV_PART_MAIN | LV_STATE_DEFAULT);

}
