// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp32_p4_eye_factory

#include "../ui.h"

void ui_ScreenAlbum_screen_init(void)
{
    ui_ScreenAlbum = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAlbum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageScreenAlbum = lv_canvas_create(ui_ScreenAlbum);
    lv_obj_set_width(ui_ImageScreenAlbum, 240);
    lv_obj_set_height(ui_ImageScreenAlbum, 240);
    lv_obj_set_align(ui_ImageScreenAlbum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenAlbum, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScreenAlbum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAlbumMenu = lv_img_create(ui_ImageScreenAlbum);
    lv_img_set_src(ui_ImageAlbumMenu, &ui_img_button_menu_png);
    lv_obj_set_width(ui_ImageAlbumMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAlbumMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAlbumMenu, 100);
    lv_obj_set_y(ui_ImageAlbumMenu, -47);
    lv_obj_set_align(ui_ImageAlbumMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAlbumMenu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAlbumMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAlbumUp = lv_img_create(ui_ImageScreenAlbum);
    lv_img_set_src(ui_ImageAlbumUp, &ui_img_up_button_png);
    lv_obj_set_width(ui_ImageAlbumUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAlbumUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAlbumUp, 100);
    lv_obj_set_y(ui_ImageAlbumUp, 0);
    lv_obj_set_align(ui_ImageAlbumUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAlbumUp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAlbumUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAlbumDown = lv_img_create(ui_ImageScreenAlbum);
    lv_img_set_src(ui_ImageAlbumDown, &ui_img_button_down_png);
    lv_obj_set_width(ui_ImageAlbumDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAlbumDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAlbumDown, 100);
    lv_obj_set_y(ui_ImageAlbumDown, 55);
    lv_obj_set_align(ui_ImageAlbumDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAlbumDown, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAlbumDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
