// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: eye_s3_product_test

#ifndef _EYE_S3_PRODUCT_TEST_UI_H
#define _EYE_S3_PRODUCT_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenSpeech
void ui_ScreenSpeech_screen_init(void);
extern lv_obj_t * ui_ScreenSpeech;
extern lv_obj_t * ui_LabelSpeech;
// SCREEN: ui_ScreenColor
void ui_ScreenColor_screen_init(void);
extern lv_obj_t * ui_ScreenColor;
// SCREEN: ui_ScreenButton
void ui_ScreenButton_screen_init(void);
extern lv_obj_t * ui_ScreenButton;
extern lv_obj_t * ui_PanelMenu;
extern lv_obj_t * ui_PanelDown;
extern lv_obj_t * ui_PanelPlay;
extern lv_obj_t * ui_PanelUp;
// SCREEN: ui_ScreenCamera
void ui_ScreenCamera_screen_init(void);
extern lv_obj_t * ui_ScreenCamera;
// SCREEN: ui_ScreenIMU
void ui_ScreenIMU_screen_init(void);
extern lv_obj_t * ui_ScreenIMU;
extern lv_obj_t * ui_LabelPass;
extern lv_obj_t * ui_LabelPrompt;
// SCREEN: ui_ScreenSuccess
void ui_ScreenSuccess_screen_init(void);
extern lv_obj_t * ui_ScreenSuccess;
extern lv_obj_t * ui_LabelSuccess;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1924961647);    // assets/coffee-1839734_1280.png
LV_IMG_DECLARE(ui_img_1545807356);    // assets/coffee-1974841_1280.png
LV_IMG_DECLARE(ui_img_1126967247);    // assets/coffee-cup-2317201_1280.png
LV_IMG_DECLARE(ui_img_1706561437);    // assets/coffee-pic1.png
LV_IMG_DECLARE(ui_img_424947501);    // assets/coffee-pic3.png
LV_IMG_DECLARE(ui_img_1184979050);    // assets/coffee-pic4.png
LV_IMG_DECLARE(ui_img_coffee_pic_2_png);    // assets/coffee_pic_2.png
LV_IMG_DECLARE(ui_img_374834912);    // assets/drink-pic4.png
LV_IMG_DECLARE(ui_img_1283678341);    // assets/neon-sign-4343663_1280.png


LV_FONT_DECLARE(ui_font_FontPromt);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
