// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: p4_eye_timed_shoot

#include "../ui.h"

void ui_ScreenUSB_screen_init(void)
{
    ui_ScreenUSB = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenUSB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenUSB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenUSB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUSB = lv_label_create(ui_ScreenUSB);
    lv_obj_set_width(ui_LabelUSB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUSB, -12);
    lv_obj_set_y(ui_LabelUSB, -15);
    lv_obj_set_align(ui_LabelUSB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSB,
                      "            USB has been inserted\n         \n            Please press the Reset   \n                       \n         button to restore the device.");
    lv_obj_set_style_text_color(ui_LabelUSB, lv_color_hex(0xDED7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUSB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUSB, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
