// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: p4_eye_timed_shoot

#include "../ui.h"

void ui_ScreenSet_screen_init(void)
{
    ui_ScreenSet = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSet = lv_label_create(ui_ScreenSet);
    lv_obj_set_width(ui_LabelSet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSet, -2);
    lv_obj_set_y(ui_LabelSet, 63);
    lv_obj_set_align(ui_LabelSet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSet, "Set time: 5 minutes\n\n\n\n\n\n\n");
    lv_obj_set_style_text_font(ui_LabelSet, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
